# Generated by Django 3.1.4 on 2021-01-13 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Select Date')),
                ('article_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('keyphrase', models.CharField(blank=True, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blogger', to=settings.AUTH_USER_MODEL, verbose_name='Ronny Dsouza ')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Ronny Dsouza')),
                ('comment_content', models.CharField(max_length=200, verbose_name='Blogger')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogger.article', verbose_name='Descpition')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
